openapi: 3.0.3
info:
    title: User Service
    description: Service for User CRUD
    version: "1.0"
servers:
    - url: http://localhost:8089
paths:
    /auth/token:
        post:
            tags:
                - user
            summary: token user
            operationId: user#token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            email: meridamotore@gmail.com
                            password: MyP@ssw0rd
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ab et ad id debitis voluptatem.
                            example: Consectetur et quod explicabo.
    /user:
        get:
            tags:
                - user
            summary: read user
            operationId: user#read
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Architecto provident aliquid.
                            example: Eum temporibus ducimus ipsum magni nisi iure.
            security:
                - jwt_header_Authorization:
                    - api:access
    /users/create:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            email: meridamotore@gmail.com
                            password: MyP@ssw0rd
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quia quis voluptates quia.
                            example: Temporibus saepe facilis.
    /users/delete:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteRequestBody'
                        example:
                            id: 3314748119486640210
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Officiis consequatur qui qui velit.
                            example: Aspernatur minus eius et magni quae magnam.
            security:
                - jwt_header_Authorization:
                    - api:access
    /users/update:
        put:
            tags:
                - user
            summary: update user
            operationId: user#update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            address: Ea ex.
                            name: Autem dolores nihil aperiam.
                            phone: Consequatur a.
                            surname: Et cupiditate consectetur ullam ullam sed pariatur.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quos consectetur debitis sit adipisci.
                            example: Quisquam consequuntur cumque et labore odio expedita.
            security:
                - jwt_header_Authorization:
                    - api:access
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User's email address
                    example: meridamotore@gmail.com
                    pattern: ^[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$
                password:
                    type: string
                    description: User's password
                    example: MyP@ssw0rd
            description: Create user
            example:
                email: meridamotore@gmail.com
                password: MyP@ssw0rd
        DeleteRequestBody:
            type: object
            properties:
                id:
                    type: integer
                    description: Delete id
                    example: 8731192131059646715
            example:
                id: 6420472635164768664
        UpdateRequestBody:
            type: object
            properties:
                address:
                    type: string
                    description: User address
                    example: Ad laboriosam quod est unde.
                name:
                    type: string
                    description: User name
                    example: Et assumenda quia repellendus illum iure maiores.
                phone:
                    type: string
                    description: phone
                    example: Praesentium eum eum.
                surname:
                    type: string
                    description: User surname
                    example: Debitis qui.
            description: Create user
            example:
                address: Vel sunt.
                name: Impedit fugit explicabo consequatur nulla.
                phone: Quam quam voluptas.
                surname: Sed quo ad rerum ratione.
    securitySchemes:
        jwt_header_Authorization:
            type: http
            scheme: bearer
tags:
    - name: user
      description: CRUD for users
